# Generated by Django 4.1 on 2024-06-16 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0010_rename_birth_date_person_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdaSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('similarity', models.DecimalField(decimal_places=7, max_digits=8)),
                ('movie_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldasimilarity_set_1', to='homepage.movies')),
                ('movie_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldasimilarity_set_2', to='homepage.movies')),
            ],
            options={
                'db_table': 'lda_similarity',
            },
        ),
    ]
