# Generated by Django 4.1 on 2024-08-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0004_rename_colsimilarity_cfsimilarity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LdaSimilarity',
        ),
    ]
