# Generated by Django 4.1 on 2024-04-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_images_image_alter_images_is_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='is_poster',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='adult',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
