# Generated by Django 4.1 on 2024-04-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_images_image_alter_images_is_poster_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': False},
        ),
    ]
