# Generated by Django 4.1 on 2024-04-01 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_images_options_alter_movies_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={},
        ),
    ]
