# Generated by Django 4.1 on 2024-04-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_genres_ratings_movies_rating_ratings_movie_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genres',
            table='genres',
        ),
        migrations.AlterModelTable(
            name='ratings',
            table='ratings',
        ),
    ]
