# Generated by Django 4.1 on 2024-06-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_ratings_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, null=True)),
                ('character', models.CharField(max_length=255, null=True)),
                ('job', models.CharField(max_length=255, null=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.movies')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.person')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_credits',
            field=models.ManyToManyField(blank=True, through='homepage.Credits', to='homepage.person'),
        ),
    ]
