# Generated by Django 4.1 on 2024-06-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_person_movies_description_credits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birth_date',
            new_name='birthday',
        ),
    ]
