# Generated by Django 4.1 on 2024-08-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_rename_ml_user_mlratings_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlratings',
            old_name='score',
            new_name='rating',
        ),
    ]
