# Generated by Django 4.1 on 2024-08-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_rename_score_mlratings_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlratings',
            old_name='user',
            new_name='score',
        ),
    ]
