# Generated by Django 4.1 on 2024-08-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_rename_user_mlratings_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlratings',
            old_name='rating',
            new_name='user',
        ),
    ]
